#!/usr/bin/env python3
import json
import sys
from gevent.pywsgi import WSGIServer
from rf_runner.api import app
from rf_runner.runner import Runner
from rf_runner.arg_parser import ArgParser


def main():
    if len(sys.argv) >= 2:
        ap = ArgParser()
        c = ap.get_config()
        r = Runner(c)
        r.run()
    else:
        http_server = WSGIServer(('', 5000), app)
        http_server.serve_forever()


if __name__ == "__main__":
    main()
