#!/usr/bin/env python3
import json
import sys
from gevent.pywsgi import WSGIServer
from rf_runner.api import app
from rf_runner.runner import Runner


def main():
    if len(sys.argv) == 2:
        with open(sys.argv[1]) as json_file:
            data = json.load(json_file)
            r = Runner(data)
            r.run()
    else:
        http_server = WSGIServer(('', 5000), app)
        http_server.serve_forever()


if __name__ == "__main__":
    main()
