apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rf-service.fullname" . }}-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rf-service.fullname" . }}-admin-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "rf-service.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.bindToClusterRole }}
  apiGroup: rbac.authorization.k8s.io