apiVersion: v1
kind: Service
metadata:
  name: {{ include "rf-service.fullname" . }}-caddy
  labels:
    {{- include "rf-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.caddy.service.type }}
  ports:
    - port: {{ .Values.caddy.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rf-service.selectorLabels" . | nindent 4 }}
